//
export default {
  c2: `https://oss.in-hope.cn/xiaoan/web_static/stockholder_c2.png?${Math.random()}`,
  c3: `https://oss.in-hope.cn/xiaoan/web_static/stockholder_c3.png?${Math.random()}`,
  c4: `https://oss.in-hope.cn/xiaoan/web_static/stockholder_c4.png?${Math.random()}`,
  c5: `https://oss.in-hope.cn/xiaoan/web_static/stockholder_c5.png?${Math.random()}`,
  danger: `https://oss.in-hope.cn/xiaoan/web_static/stockholder_danger.png?${Math.random()}`,
  delete: `https://oss.in-hope.cn/xiaoan/web_static/stockholder_delete.png?${Math.random()}`,
  edit: `https://oss.in-hope.cn/xiaoan/web_static/stockholder_edit.png?${Math.random()}`,
  holder: `https://oss.in-hope.cn/xiaoan/web_static/stockholder_holder.png?${Math.random()}`,
  investment: `https://oss.in-hope.cn/xiaoan/web_static/stockholder_investment.png?${Math.random()}`,
  left: `https://oss.in-hope.cn/xiaoan/web_static/stockholder_left.png?${Math.random()}`,
  member: `https://oss.in-hope.cn/xiaoan/web_static/stockholder_member.png?${Math.random()}`,
  menu1: `https://oss.in-hope.cn/xiaoan/web_static/stockholder_menu1.png?${Math.random()}`,
  menu2: `https://oss.in-hope.cn/xiaoan/web_static/stockholder_menu2.png?${Math.random()}`,
  menu3: `https://oss.in-hope.cn/xiaoan/web_static/stockholder_menu3.png?${Math.random()}`,
  menu4: `https://oss.in-hope.cn/xiaoan/web_static/stockholder_menu4.png?${Math.random()}`,
  menu5: `https://oss.in-hope.cn/xiaoan/web_static/stockholder_menu5.png?${Math.random()}`,
  menu6: `https://oss.in-hope.cn/xiaoan/web_static/stockholder_menu6.png?${Math.random()}`,
  menubg: `https://oss.in-hope.cn/xiaoan/web_static/stockholder_menubg.png?${Math.random()}`,
  right: `https://oss.in-hope.cn/xiaoan/web_static/stockholder_right.png?${Math.random()}`,
  set: `https://oss.in-hope.cn/xiaoan/web_static/stockholder_set.png?${Math.random()}`,
  show: `https://oss.in-hope.cn/xiaoan/web_static/stockholder_show.png?${Math.random()}`,
  tips: `https://oss.in-hope.cn/xiaoan/web_static/stockholder_tips.png?${Math.random()}`
}
