//
export default {
  add: `https://oss.in-hope.cn/xiaoan/web_static/xh_add.png?${Math.random()}`,
  attent: `https://oss.in-hope.cn/xiaoan/web_static/xh_attent.png?${Math.random()}`,
  attentyet: `https://oss.in-hope.cn/xiaoan/web_static/xh_attentyet.png?${Math.random()}`,
  closefoc: `https://oss.in-hope.cn/xiaoan/web_static/xh_closefoc.png?${Math.random()}`,
  edit: `https://oss.in-hope.cn/xiaoan/web_static/xh_edit.png?${Math.random()}`,
  edittopic: `https://oss.in-hope.cn/xiaoan/web_static/xh_edittopic.png?${Math.random()}`,
  foc: `https://oss.in-hope.cn/xiaoan/web_static/xh_foc.png?${Math.random()}`,
  headerImg: `https://oss.in-hope.cn/xiaoan/web_static/xh_headerImg.png?${Math.random()}`,
  hotTopic: `https://oss.in-hope.cn/xiaoan/web_static/xh_hotTopic.png?${Math.random()}`,
  invite: `https://oss.in-hope.cn/xiaoan/web_static/xh_invite.png?${Math.random()}`,
  inviteyet: `https://oss.in-hope.cn/xiaoan/web_static/xh_inviteyet.png?${Math.random()}`,
  maTop: `https://oss.in-hope.cn/xiaoan/web_static/xh_maTop.png?${Math.random()}`,
  questionadd: `https://oss.in-hope.cn/xiaoan/web_static/xh_question-add.png?${Math.random()}`,
  questionaddyet: `https://oss.in-hope.cn/xiaoan/web_static/xh_question-addyet.png?${Math.random()}`,
  refresh: `https://oss.in-hope.cn/xiaoan/web_static/xh_refresh.png?${Math.random()}`,
  relatedQuestion: `https://oss.in-hope.cn/xiaoan/web_static/xh_relatedQuestion.png?${Math.random()}`,
  rz: `https://oss.in-hope.cn/xiaoan/web_static/xh_rz.png?${Math.random()}`,
  show: `https://oss.in-hope.cn/xiaoan/web_static/xh_show.png?${Math.random()}`,
  v: `https://oss.in-hope.cn/xiaoan/web_static/xh_v.png?${Math.random()}`,
  write: `https://oss.in-hope.cn/xiaoan/web_static/xh_write.png?${Math.random()}`,
  xhAdmin: `https://oss.in-hope.cn/xiaoan/web_static/xh_Admin.png?${Math.random()}`,
  xhCollect: `https://oss.in-hope.cn/xiaoan/web_static/xh_Collect.png?${Math.random()}`,
  xhLaud: `https://oss.in-hope.cn/xiaoan/web_static/xh_Laud.png?${Math.random()}`,
  xhUser: `https://oss.in-hope.cn/xiaoan/web_static/xh_User.png?${Math.random()}`,
  zhan3x: `https://oss.in-hope.cn/xiaoan/web_static/xh_zhan3x.png?${Math.random()}`
}
