
export default {
  Attribute: `https://oss.in-hope.cn/xiaoan/h5_static/rules/Attribute.png?${Math.random()}`,
  InABatch: `https://oss.in-hope.cn/xiaoan/h5_static/rules/InABatch.png?${Math.random()}`,
  Toleft: `https://oss.in-hope.cn/xiaoan/h5_static/rules/Toleft.jpg?${Math.random()}`,
  adjunct: `https://oss.in-hope.cn/xiaoan/h5_static/rules/adjunct@3x.png?${Math.random()}`,
  anli: `https://oss.in-hope.cn/xiaoan/h5_static/rules/anli.png?${Math.random()}`,
  bottom: `https://oss.in-hope.cn/xiaoan/h5_static/rules/bottom.png?${Math.random()}`,
  celloctIcon: `https://oss.in-hope.cn/xiaoan/h5_static/rules/celloctIcon.png?${Math.random()}`,
  chengseduigou: `https://oss.in-hope.cn/xiaoan/h5_static/rules/chengseduigou.png?${Math.random()}`,
  clear: `https://oss.in-hope.cn/xiaoan/h5_static/rules/clear.png?${Math.random()}`,
  correlation: `https://oss.in-hope.cn/xiaoan/h5_static/rules/correlation.png?${Math.random()}`,
  editimg: `https://oss.in-hope.cn/xiaoan/h5_static/rules/editimg.png?${Math.random()}`,
  grayStar: `https://oss.in-hope.cn/xiaoan/h5_static/rules/grayStar.png?${Math.random()}`,
  home: `https://oss.in-hope.cn/xiaoan/h5_static/rules/home.png?${Math.random()}`,
  linkIcon: `https://oss.in-hope.cn/xiaoan/h5_static/rules/linkIcon.png?${Math.random()}`,
  listmenu: `https://oss.in-hope.cn/xiaoan/h5_static/rules/listmenu.png?${Math.random()}`,
  lose: `https://oss.in-hope.cn/xiaoan/h5_static/rules/lose.png?${Math.random()}`,
  return: `https://oss.in-hope.cn/xiaoan/h5_static/rules/return.png?${Math.random()}`,
  right: `https://oss.in-hope.cn/xiaoan/h5_static/rules/right.png?${Math.random()}`,
  rightOrange: `https://oss.in-hope.cn/xiaoan/h5_static/rules/rightOrange.png?${Math.random()}`,
  roadShow: `https://oss.in-hope.cn/xiaoan/h5_static/rules/roadShow.jpg?${Math.random()}`,
  selectImg: `https://oss.in-hope.cn/xiaoan/h5_static/rules/selectImg.png?${Math.random()}`,
  selectImgUp: `https://oss.in-hope.cn/xiaoan/h5_static/rules/selectImgUp.png?${Math.random()}`,
  share: `https://oss.in-hope.cn/xiaoan/h5_static/rules/share.png?${Math.random()}`,
  shareIcon: `https://oss.in-hope.cn/xiaoan/h5_static/rules/shareIcon.png?${Math.random()}`,
  shareImg: `https://oss.in-hope.cn/xiaoan/h5_static/rules/shareImg.png?${Math.random()}`,
  star: `https://oss.in-hope.cn/xiaoan/h5_static/rules/star.png?${Math.random()}`,
  tobeEffective: `https://oss.in-hope.cn/xiaoan/h5_static/rules/tobeEffective.png?${Math.random()}`,
  tobutton: `https://oss.in-hope.cn/xiaoan/h5_static/rules/tobutton.png?${Math.random()}`,
  top: `https://oss.in-hope.cn/xiaoan/h5_static/rules/top.png?${Math.random()}`,
  toright: `https://oss.in-hope.cn/xiaoan/h5_static/rules/toright.png?${Math.random()}`,
  trySenior: `https://oss.in-hope.cn/xiaoan/h5_static/rules/trySenior.png?${Math.random()}`,
  x: `https://oss.in-hope.cn/xiaoan/h5_static/rules/x.jpg?${Math.random()}`,
}
