export default {
  agree1: `https://oss.in-hope.cn/xiaoan/h5_static/xinhu/agree1.png?${Math.random()}`,
  agree2: `https://oss.in-hope.cn/xiaoan/h5_static/xinhu/agree2.png?${Math.random()}`,
  answer: `https://oss.in-hope.cn/xiaoan/h5_static/xinhu/answer.png?${Math.random()}`,
  edit: `https://oss.in-hope.cn/xiaoan/h5_static/xinhu/edit.png?${Math.random()}`,
  focusHT: `https://oss.in-hope.cn/xiaoan/h5_static/xinhu/focusHT.png?${Math.random()}`,
  guide1: `https://oss.in-hope.cn/xiaoan/h5_static/xinhu/guide1.png?${Math.random()}`,
  guide2: `https://oss.in-hope.cn/xiaoan/h5_static/xinhu/guide2.png?${Math.random()}`,
  guide3: `https://oss.in-hope.cn/xiaoan/h5_static/xinhu/guide3.png?${Math.random()}`,
  guide4: `https://oss.in-hope.cn/xiaoan/h5_static/xinhu/guide4.png?${Math.random()}`,
  guide5: `https://oss.in-hope.cn/xiaoan/h5_static/xinhu/guide5.png?${Math.random()}`,
  guide6: `https://oss.in-hope.cn/xiaoan/h5_static/xinhu/guide6.png?${Math.random()}`,
  guide7: `https://oss.in-hope.cn/xiaoan/h5_static/xinhu/guide7.png?${Math.random()}`,
  headerImg: `https://oss.in-hope.cn/xiaoan/h5_static/xinhu/headerImg.png?${Math.random()}`,
  hot: `https://oss.in-hope.cn/xiaoan/h5_static/xinhu/hot.png?${Math.random()}`,
  huati: `https://oss.in-hope.cn/xiaoan/h5_static/xinhu/huati.png?${Math.random()}`,
  knowbtn: `https://oss.in-hope.cn/xiaoan/h5_static/xinhu/knowbtn.png?${Math.random()}`,
  qdelete: `https://oss.in-hope.cn/xiaoan/h5_static/xinhu/qdelete.png?${Math.random()}`,
  qedit: `https://oss.in-hope.cn/xiaoan/h5_static/xinhu/qedit.png?${Math.random()}`,
  questionadd: `https://oss.in-hope.cn/xiaoan/h5_static/xinhu/question-add.png?${Math.random()}`,
  questionaddyet: `https://oss.in-hope.cn/xiaoan/h5_static/xinhu/question-addyet.png?${Math.random()}`,
  rz: `https://oss.in-hope.cn/xiaoan/h5_static/xinhu/rz.png?${Math.random()}`,
  show: `https://oss.in-hope.cn/xiaoan/h5_static/xinhu/show.png?${Math.random()}`,
  tiwen: `https://oss.in-hope.cn/xiaoan/h5_static/xinhu/tiwen.png?${Math.random()}`
}
